apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-trunfo
  labels:
    app: super-trunfo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: super-trunfo
  template:
    metadata:
      labels:
        app: super-trunfo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: super-trunfo
          image: carloszan/super-trunfo-camara-app:latest
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          readinessProbe:
            httpGet:
              port: web
              path: /
          imagePullPolicy: "Always"
