name: Docker Image CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps
    - uses: uraimo/run-on-arch-action@v2.1.1
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --platform linux/arm64 --tag carloszan/politicians:$(date +%s)
